apiVersion: v1
kind: Secret
metadata:
  name: trace-llm-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  MONGODB_URI: "mongodb://trace-llm-mongo:27017/tracellm"
  REDIS_URL: "redis://trace-llm-redis:6379"
